name: Deploy para VPS Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Adiciona a chave pública do host para evitar erros de verificação
      - name: Adicionar chave do host
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Configurar Chave SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Deploy na VPS
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }} << 'EOF'
            cd /home/pedro/banco-de-questoes-api

            echo "--> Baixando a versão mais recente do código..."
            git pull origin main || { echo "Falha ao atualizar o código. Abortando o deploy." && exit 1; }

            echo "--> Reconstruindo e reiniciando os contêineres..."
            docker-compose build
            docker-compose up -d

            echo "--> Executando o script de migração..."
            docker exec mysql_banco_de_questoes mysql -u root -psenha BancoDeQuestoes -e "TRUNCATE TABLE questoes_oab;"
            node migracao.js
          
            echo "--> Deploy concluído com sucesso!"
          EOF