name: Deploy para VPS Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Autentica e baixa o código do GitHub no servidor do Actions
      - name: Checkout do código
        uses: actions/checkout@v4

      # 2. Faz o deploy dos arquivos para a VPS com rsync via SSH
      - name: Sincronizar arquivos para a VPS
        uses: burnettk/rsync-action@master
        with:
          ssh_private_key: ${{ secrets.VPS_SSH_KEY }}
          ssh_host: ${{ secrets.VPS_HOST }}
          ssh_user: ${{ secrets.VPS_USERNAME }}
          ssh_port: 22
          source: ./
          target: /home/pedro/banco-de-questoes-api/

      # 3. Conecta na VPS e executa os comandos de Docker
      - name: Executar comandos na VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            # NAVEGUE ATÉ A PASTA DO PROJETO NA VPS
            cd /home/pedro/banco-de-questoes-api

            # Reconstrói e reinicia os contêineres com Docker Compose
            echo "--> Reconstruindo e reiniciando os contêineres..."
            docker-compose build
            docker-compose up -d

            # Executa o script de migração de forma segura
            echo "--> Executando o script de migração..."
            docker exec mysql_banco_de_questoes mysql -u root -psenha BancoDeQuestoes -e "TRUNCATE TABLE questoes_oab;"
            node migracao.js
            
            echo "--> Deploy concluído com sucesso!"