name: Deploy para VPS Hostinger

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Faz o checkout do código do seu repositório
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configura a chave SSH para acesso seguro ao VPS
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.2
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      # 3. Copia os arquivos do projeto para a VPS com rsync
      - name: Sincronizar arquivos para a VPS
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no -i $SSH_AUTH_SOCK" \
          ./ ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_HOST }}:/home/${{ secrets.VPS_USERNAME }}/banco-de-questoes-api

      # 4. Acessa a VPS e executa os comandos de deploy com Docker Compose
      - name: Executar comandos na VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            # Navega até à pasta do projeto no servidor
            cd /home/${{ secrets.VPS_USERNAME }}/banco-de-questoes-api
            
            # Para e remove os containers antigos
            docker-compose down
            
            # Constrói e inicia os novos containers em segundo plano
            docker-compose up --build -d

            # Executa o script de migração de forma segura
            echo "--> Executando o script de migração..."
            docker exec mysql_banco_de_questoes mysql -u root -psenha BancoDeQuestoes -e "TRUNCATE TABLE questoes_oab;"
            node migracao.js
            
            echo "--> Deploy concluído com sucesso!"